# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         WEC-FastCGI
version:      0.01
version_from: FastCGI.pm
installdirs:  site
requires:
    Exporter::Tidy:                0.05
    Test::More:                    0.11
    WEC:                           0.01

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
